---
- hosts: ec2_ips
  become: true

  tasks:
    - name: check docker
      ansible.builtin.command: docker --versio
      ignore_errors: yes

    - name: Install docker for ubuntu
      ansible.builtin.apt:
        update_cache: yes
        name: docker.io
        state: present
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']
      ignore_errors: yes
    - name: Install docker for linux
      ansible.builtin.yum:
        update_cache: yes
        name: docker
        state: latest
      when: ansible_facts['distribution'] in ['Redhat', 'Amazon']
      ignore_errors: yes
